import { beforeEach, expect, test, vi } from 'vitest';
import { emotions, limitText, sampleStars, validateMessage } from '../src/domain';
import { previewSeeds } from '../src/seeds';
import * as api from '../src/api';
function storage(){const data=new Map<string,string>();return {getItem:(k:string)=>data.get(k)||null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)};}
beforeEach(()=>{vi.stubGlobal('localStorage',storage());vi.stubGlobal('sessionStorage',storage());});
test('all six pools have ten valid draft messages; no hidden or duplicate samples',()=>{for(const e of emotions){const pool=previewSeeds.filter(s=>s.emotion===e.id);expect(pool).toHaveLength(10);pool.forEach(s=>expect(validateMessage(s.content,s.emotion)).toBeNull());const result=sampleStars([...pool,...pool,{...pool[0],id:'hidden',status:'hidden'}],e.id);expect(result).toHaveLength(6);expect(new Set(result.map(s=>s.id)).size).toBe(6);expect(result.some(s=>s.id==='hidden')).toBe(false);}expect(Array.from(limitText('🌟'.repeat(121)))).toHaveLength(120);expect(validateMessage('  ','tired')).not.toBeNull();});
test('guest submissions stay outside account history and repeated requests create only one star',async()=>{const id=crypto.randomUUID();const first=await api.submit('ค่อย ๆ ไปได้นะ','tired',id,'');expect((await api.submit(first.content,'tired',id,'')).id).toBe(first.id);await expect(api.submit('เปลี่ยนข้อความ','tired',id,'')).rejects.toThrow();expect((await api.getPool('tired')).some(s=>s.id===first.id)).toBe(false);await api.signIn();expect(await api.getHistory()).toHaveLength(0);await api.submit('วันนี้พักได้','tired',crypto.randomUUID(),'');expect(await api.getHistory()).toHaveLength(1);});
test('save is idempotent and moderation removes saved and public content',async()=>{await api.signIn();const star=(await api.getPool('tired'))[0];expect(await api.saveStar(star.id)).toEqual({added:true});expect(await api.saveStar(star.id)).toEqual({added:false});await api.reportStar(star.id,'hurtful','');await api.moderate(star.id,'hidden','ทดสอบซ่อนข้อความ');const saved=await api.getSaved();expect(saved).toHaveLength(1);expect(saved[0].content).toBe('');expect(saved[0].unavailable).toBe(true);await expect(api.getStar(star.id)).rejects.toThrow();await expect(api.saveStar(star.id)).rejects.toThrow();expect((await api.getQueue()).reports).toHaveLength(0);await api.signOut();await expect(api.getQueue()).rejects.toThrow();await expect(api.moderate(star.id,'approved','ทดสอบ')).rejects.toThrow();});
test('updated team copy preserves saved identity and moderation without rewriting community content',async()=>{await api.signIn();const seed=previewSeeds[0];const userStar={...seed,id:crypto.randomUUID(),source:'community',content:'ข้อความของผู้ใช้ต้องคงเดิม'};localStorage.setItem('ooca.preview.data.v1',JSON.stringify({stars:[{...seed,content:'ข้อความทีมเวอร์ชันเก่า'},userStar],saves:{[seed.id]:'2026-09-07T00:00:00Z'},own:[],requests:{},reports:[]}));expect((await api.getSaved())[0]).toMatchObject({id:seed.id,content:seed.content});expect((await api.getStar(userStar.id)).content).toBe(userStar.content);await api.moderate(seed.id,'hidden','ทดสอบ');expect((await api.getSaved())[0]).toMatchObject({id:seed.id,content:'',unavailable:true});});
