import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { codePointLength, emotionById, emotions, limitText, relativeDate, starAsset } from './domain';
import type { EmotionId, ReviewStar, Star, User } from './domain';
import * as api from './api';
import { Turnstile } from './Turnstile';

type Page = 'home'|'feeling'|'sky'|'read'|'write'|'preview'|'fold'|'sent'|'jar'|'history'|'admin'|'privacy'|'terms';
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{ref.current?.close();previous?.focus();};},[]);
  return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();close();}} aria-label={title}><div className="modal-header"><h2>{title}</h2><button className="link" onClick={close}>ปิด</button></div>{children}</dialog>;
}
function Paper({star,step=3}:{star:Star;step?:number}) {return <div className="paper"><img src={starAsset(star.emotion,step)} alt={step===3?'กระดาษดาวที่คลี่ออก':'ดาวกระดาษ'}/>{step===3&&<p>{star.content}</p>}</div>;}
const positions=[[33,5],[8,30],[67,24],[27,56],[81,60],[57,83]];
function Sky({stars,selected,onSelect,paused=false}:{stars:Star[];selected?:string;onSelect:(star:Star)=>void;paused?:boolean}) {
  const reduced=useReducedMotion();
  return <div className="star-field" aria-label="เลือกดาวที่อยากอ่าน">{stars.map((s,i)=><button key={s.id} className={`floating-star ${selected===s.id?'selected':''}`} style={{left:`${positions[i%6][0]}%`,top:`${positions[i%6][1]}%`,animationDuration:`${18+i}s`,animationDelay:`${-i*3}s`,animationPlayState:paused||selected||reduced?'paused':'running'}} aria-label={`เลือกดาวดวงที่ ${i+1}`} aria-pressed={selected===s.id} onClick={()=>onSelect(s)}><img src={starAsset(s.emotion)} alt=""/></button>)}</div>;
}
function Fold({star,done}:{star:Star;done:()=>void}) {
  const reduced=useReducedMotion();const [step,setStep]=useState(3);const doneRef=useRef(done);doneRef.current=done;
  useEffect(()=>{const timers=reduced?[setTimeout(()=>doneRef.current(),20)]:[setTimeout(()=>setStep(2),750),setTimeout(()=>setStep(1),2500),setTimeout(()=>setStep(0),4250),setTimeout(()=>doneRef.current(),6000)];return()=>timers.forEach(clearTimeout);},[reduced]);
  return <><h1>กำลังพับเป็นดาว…</h1><div className="paper folding"><AnimatePresence initial={false}><motion.div key={step} className="fold-layer" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:1}}><Paper star={star} step={step}/></motion.div></AnimatePresence></div><p>ขอบคุณที่เขียนข้อความนี้</p></>;
}
function Unfold({star}:{star:Star}) {
  const reduced=useReducedMotion();const [step,setStep]=useState(reduced?3:0);
  useEffect(()=>{if(reduced){setStep(3);return;}const timers=[1,2,3].map(i=>setTimeout(()=>setStep(i),i*750));return()=>timers.forEach(clearTimeout);},[reduced]);
  return <div className="paper folding"><AnimatePresence initial={false}><motion.div key={step} className="fold-layer" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.75}}><Paper star={star} step={step}/></motion.div></AnimatePresence></div>;
}
function SentStar({star,paused,open}:{star:Star;paused:boolean;open:()=>void}) {
  const ref=useRef<HTMLButtonElement>(null);const anim=useRef<Animation|null>(null);const reduced=useReducedMotion();
  useEffect(()=>{if(reduced)return;anim.current=ref.current!.animate([{transform:'translate(-50%,0)',opacity:1},{transform:'translate(calc(-50% + 20px),-180px)',opacity:1,offset:.5},{transform:'translate(calc(-50% - 10px),-460px)',opacity:0}],{duration:12000,fill:'forwards',easing:'linear'});return()=>anim.current?.cancel();},[star.id,reduced]);
  useEffect(()=>{if(paused)anim.current?.pause();else anim.current?.play();},[paused]);
  return <button ref={ref} className="sent-star" onClick={open} aria-label="อ่านดาวที่เพิ่งส่ง"><img src={starAsset(star.emotion)} alt="ดาวของคุณ"/></button>;
}
export default function App() {
  const [page,setPage]=useState<Page>('home');const [user,setUser]=useState<User|null>(null);
  const [emotion,setEmotion]=useState<EmotionId>('tired');const [pool,setPool]=useState<Star[]>([]);const [selected,setSelected]=useState<Star|null>(null);
  const [draft,setDraft]=useState('');const [draftEmotion,setDraftEmotion]=useState<EmotionId|null>(null);const [sent,setSent]=useState<Star|null>(null);
  const [saved,setSaved]=useState<Star[]>([]);const [history,setHistory]=useState<Star[]>([]);const [queue,setQueue]=useState<ReviewStar[]>([]);
  const [reports,setReports]=useState<{message_id:string;reason:string}[]>([]);const [reviewReasons,setReviewReasons]=useState<Record<string,string>>({});
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const requestId=useRef(crypto.randomUUID());
  const [modal,setModal]=useState<'login'|'menu'|'list'|'own'|'report'|null>(null);const [returnPage,setReturnPage]=useState<Page>('sky');const [pendingSave,setPendingSave]=useState(false);
  const [arrival,setArrival]=useState<string|null>(null);const [isMod,setIsMod]=useState(false);const [reportReason,setReportReason]=useState('hurtful');
  const [captchaToken,setCaptchaToken]=useState('');const [reportToken,setReportToken]=useState('');const [captchaReset,setCaptchaReset]=useState(0);
  const reduced=useReducedMotion();
  const go=(next:Page)=>{setError('');setNotice('');setModal(null);setPage(next);window.scrollTo({top:0});};
  async function run(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'มีบางอย่างขัดข้อง ลองอีกครั้งนะ');}finally{lock.current=false;setBusy(false);}}
  useEffect(()=>{api.currentUser().then(setUser).catch(()=>setError('ตอนนี้เปิดบัญชีทดลองไม่ได้'));},[]);
  useEffect(()=>{api.isModerator().then(setIsMod).catch(()=>setIsMod(false));},[user]);
  useEffect(()=>{const handler=()=>{setModal(null);setPage('home');setSelected(null);};window.addEventListener('popstate',handler);return()=>window.removeEventListener('popstate',handler);},[]);
  useEffect(()=>{if(!arrival)return;const timer=setTimeout(()=>setArrival(null),reduced?20:2050);return()=>clearTimeout(timer);},[arrival,reduced]);
  async function chooseFeeling(id:EmotionId){await run(async()=>{setEmotion(id);setSelected(null);setPool(await api.getPool(id));go('sky');});}
  const write=()=>{requestId.current=crypto.randomUUID();setDraft('');setDraftEmotion(null);go('write');};
  async function openJar(){if(!user&&!api.localJarMode){setPendingSave(false);setModal('login');return;}await run(async()=>{setSaved(await api.getSaved());go('jar');});}
  async function persistStar(){if(!selected)return;const result=await api.saveStar(selected.id);setSaved(await api.getSaved());go('jar');setArrival(result.added?selected.id:null);if(!result.added)setNotice('เก็บดาวดวงนี้ไว้ในโถแล้ว');}
  async function save(){if(!user&&!api.localJarMode){setPendingSave(true);setModal('login');return;}await run(persistStar);}
  async function login(){await run(async()=>{await api.signIn();if(api.previewMode){setUser(await api.currentUser());setModal(null);if(pendingSave)await persistStar();else{setSaved(await api.getSaved());go('jar');}setPendingSave(false);}});}
  async function openHistory(){if(!user){setPendingSave(false);setModal('login');return;}await run(async()=>{setHistory(await api.getHistory());go('history');});}
  async function openRead(star:Star,from:Page){if(star.unavailable)return;await run(async()=>{const fresh=from==='history'?(await api.getHistory()).find(s=>s.id===star.id&&!s.unavailable):await api.getStar(star.id);if(!fresh)throw new Error('ข้อความนี้เปิดอ่านไม่ได้แล้ว');setSelected(fresh);setReturnPage(from);go('read');});}
  async function send(){if(!draftEmotion||api.requiresCaptcha&&!captchaToken)return;await run(async()=>{try{const star=await api.submit(draft,draftEmotion,requestId.current,captchaToken);setSent(star);go('fold');}catch(error){setCaptchaToken('');setCaptchaReset(value=>value+1);throw error;}});}
  const draftStar:Star={id:'draft',content:draft,emotion:draftEmotion||'tired',source:'community',created_at:new Date().toISOString()};
  const title=page==='write'||page==='preview'?'ฝากดาวให้ใครบางคน':page==='history'?'ดาวที่เคยเขียน':page==='admin'?'ตรวจข้อความ':page==='privacy'?'ความเป็นส่วนตัว':page==='terms'?'ข้อตกลงการใช้งาน':'';
  const back=()=>{if(page==='read')go(returnPage);else if(page==='preview')go('write');else if(page==='sky')go('feeling');else if(page==='history')go('write');else go('home');};
  function list(items:Star[],from:Page){return <div className="message-list">{items.length===0?<div className="empty"><img src="/assets/companion.png" alt=""/><h2>{from==='history'?'ยังไม่มีดาวที่เคยเขียน':'ยังไม่ได้เก็บดาวเลย'}</h2><p>{from==='history'?'ดาวที่ส่งตอนลงชื่อเข้าใช้จะอยู่ตรงนี้':'เจอข้อความที่อยากอ่านอีกเมื่อไหร่ เก็บไว้ตรงนี้ได้เลย'}</p></div>:items.map(s=><button disabled={s.unavailable} key={s.id} className="message-card" onClick={()=>{setModal(null);void openRead(s,from);}}><img src={starAsset(s.emotion)} alt=""/><span><strong>{s.unavailable?'ข้อความนี้เปิดอ่านไม่ได้แล้ว':s.content}</strong><small>{emotionById(s.emotion).label} · {relativeDate(s.saved_at||s.created_at)}</small></span><span aria-hidden="true">›</span></button>)}</div>;}
  return <div className={`app app-${page}`}>{api.previewMode&&<div className="preview-banner">กำลังทดลองในเครื่องนี้ · ข้อมูลยังไม่ส่งถึงคนอื่น {user&&'· บัญชีทดลอง'}</div>}
    <main className={`screen page-${page}`}>
      {page!=='home'&&page!=='fold'&&page!=='sent'&&<header className="navigation"><button className="link" onClick={back} disabled={busy}>ย้อนกลับ</button>{['feeling','sky','read'].includes(page)?<div className="progress"><div>{[1,2,3].map(n=><i key={n} className={n===({feeling:1,sky:2,read:3} as Record<string,number>)[page]?'current':''}/>)}</div><span>ขั้นตอน {({feeling:1,sky:2,read:3} as Record<string,number>)[page]} จาก 3</span></div>:<span>{title}</span>}<button aria-label="เปิดเมนู" className="menu-button" onClick={()=>setModal('menu')}>⋮</button></header>}
      {error&&<div role="alert" className="alert">{error}<button className="link" onClick={()=>setError('')}>ปิด</button></div>}{notice&&<p className="notice" role="status">{notice}</p>}{busy&&<p role="status" className="loading">กำลังโหลด…</p>}
      {page==='home'&&<div className="home"><div className="home-nav"><img className="logo" src="/assets/entry-logo.svg" alt="mindfull"/><button className="menu-button preview-menu" aria-label="เปิดเมนู" onClick={()=>setModal('menu')}>⋮</button></div><div className="entry-art" aria-label="อูก้ากอดดาวท่ามกลางเมฆและดาว" role="img"><img className="entry-cloud-left" src="/assets/entry-cloud-left.svg" alt=""/><img className="entry-cloud-right" src="/assets/entry-cloud-right.svg" alt=""/><img className="entry-cloud-bottom" src="/assets/entry-cloud-bottom.svg" alt=""/><img className="entry-mascot" src="/assets/entry-mascot.png" alt=""/><img className="entry-gold" src="/assets/entry-star-gold.svg" alt=""/><img className="entry-pink" src="/assets/entry-star-pink.svg" alt=""/><img className="entry-blue" src="/assets/entry-star-blue.svg" alt=""/>{[[212,25,14],[32,111,13],[19,244,13],[320,126,13],[302,279,11]].map(([x,y,size],i)=><img key={i} className="entry-sparkle" src="/assets/entry-sparkle.svg" alt="" style={{left:((x+size*.3172)/342*100)+'%',top:y+size*.3172,width:size*.3656,height:size*.3656}}/>)}</div><div className="entry-copy"><h1>วันนี้รู้สึกยังไงบ้าง?</h1><p>แวะดูความรู้สึกตัวเองสักนิด<br/>แล้วลองเปิดอ่านข้อความที่ใครบางคนฝากไว้</p><button className="primary entry-cta" onClick={()=>go('feeling')}><img src="/assets/entry-camera.svg" alt=""/>ลองเลือกความรู้สึก <span>→</span></button><hr/><button className="entry-send" onClick={write} aria-label="ฝากดาวให้ใครบางคน ＋"><span>อยากฝากกำลังใจให้ใครสักคนไหม?</span><strong>ฝากดาวให้ใครบางคน ＋</strong></button></div></div>}
      {page==='feeling'&&<section className="checkin"><h1>ตอนนี้รู้สึกแบบไหน?</h1><p>เลือกข้อที่ใกล้กับความรู้สึกตอนนี้ได้เลย</p><div className="feeling-grid">{emotions.map(e=><button disabled={busy} className="feeling-card" key={e.id} onClick={()=>void chooseFeeling(e.id)}><div className="feeling-art"><img src={`/assets/${e.art}-normal.png`} alt=""/><img className="hover-art" src={`/assets/${e.art}-hover.png`} alt=""/></div>{e.checkLabel}</button>)}</div><p className="small">ไม่มีถูกหรือผิด เลือกใหม่ได้เสมอ</p></section>}
      {page==='sky'&&<section className="sky"><h1>อยากเปิดดาวดวงไหน?</h1><p>ลองเลือกสักดวง แล้วดูว่ามีข้อความอะไรอยู่ข้างใน</p><div className="feeling-context"><img src={starAsset(emotion)} alt=""/>ความรู้สึกตอนนี้: {emotionById(emotion).label}</div>{pool.length?<><Sky stars={pool} selected={selected?.id} onSelect={setSelected}/><div className="sky-actions">{selected?<><button className="primary" onClick={()=>void openRead(selected,'sky')} disabled={busy}>เปิดดาวดวงนี้</button><button className="link" onClick={()=>setSelected(null)}>เลือกดวงอื่น</button></>:<button className="secondary" onClick={()=>setSelected(pool[Math.floor(Math.random()*pool.length)])}>ช่วยเลือกให้หน่อย</button>}</div></>:<div className="empty"><h2>ตอนนี้ยังไม่มีดาวในกลุ่มนี้</h2><p>แวะมาใหม่ได้ หรือจะลองเลือกความรู้สึกอื่นก่อนก็ได้</p><button className="secondary" onClick={()=>go('feeling')}>เลือกความรู้สึกใหม่</button></div>}<div className="sky-scenery" aria-hidden="true"><img className="sky-mascot" src="/assets/mascot-sky.png"/>{[0,1,2].map(i=><img className={`scenery-cloud cloud-${i}`} key={i} src="/assets/cloud.png"/>)}</div></section>}
      {page==='read'&&selected&&<section className="reader"><p>{selected.source==='team'?'ทีมงานฝากข้อความนี้มาให้คุณ ✦':'มีคนฝากข้อความนี้มาให้คุณ ✦'}</p><Unfold key={selected.id} star={selected}/><button className="primary" disabled={busy||returnPage==='history'} onClick={()=>void save()}>{returnPage==='history'?'ดาวที่คุณเขียน':'เก็บดาวไว้ในโถ'}</button><button className="link" onClick={write}>ฝากดาวให้ใครบางคน →</button>{returnPage!=='history'&&<button className="link quiet" onClick={()=>setModal('report')}>รายงานข้อความ</button>}</section>}
      {page==='write'&&<section className="write"><h1>วันนี้อยากฝากอะไร<br/>ถึงใครสักคน?</h1><p>ลองนึกถึงคำที่คุณอยากได้ยินในวันที่รู้สึกแบบนี้</p><label id="feelings-label">อยากฝากดาวให้คนที่กำลังรู้สึก…</label><div className="emotion-strip" role="group" aria-labelledby="feelings-label">{emotions.map(e=><button key={e.id} aria-pressed={draftEmotion===e.id} className={draftEmotion===e.id?'chosen':''} onClick={event=>{setDraftEmotion(e.id);requestId.current=crypto.randomUUID();event.currentTarget.scrollIntoView({block:'nearest',inline:'nearest',behavior:reduced?'instant':'smooth'});}}><img src={starAsset(e.id)} alt=""/><span>{e.label}</span></button>)}</div><label htmlFor="message" className="field-label">ถ้าเขารู้สึกแบบนี้ อยากบอกอะไรเขา?</label><div className="text-field"><textarea id="message" value={draft} placeholder="พิมพ์ข้อความที่อยากฝากไว้ตรงนี้…" onChange={e=>{setDraft(limitText(e.target.value));requestId.current=crypto.randomUUID();}} aria-describedby="counter"/><span id="counter">{codePointLength(draft)}/120</span></div>{!user&&<p className="small">ส่งได้เลยโดยไม่ต้องลงชื่อเข้าใช้ แต่จะกลับมาดูข้อความนี้ในประวัติไม่ได้</p>}<button className="primary" disabled={!draft.trim()||!draftEmotion} onClick={()=>go('preview')}>ดูตัวอย่างดาว</button></section>}
      {page==='preview'&&<section className="reader"><h2>เปิดดาวแล้วจะเห็นแบบนี้</h2><Paper star={draftStar}/><img className="paper-companion" src="/assets/companion.png" alt=""/><p className="small">ข้อความสั้น ๆ ก็อาจช่วยให้ใครสักคนยิ้มได้</p>{api.requiresCaptcha&&<Turnstile action="submit" resetKey={captchaReset} onToken={setCaptchaToken}/>}<button className="primary" onClick={()=>void send()} disabled={busy||api.requiresCaptcha&&!captchaToken}>พับแล้วส่งดาว ✦</button><button className="link" disabled={busy} onClick={()=>go('write')}>กลับไปแก้ข้อความ</button></section>}
      {page==='fold'&&sent&&<section className="reader fold-screen"><Fold star={sent} done={()=>go('sent')}/></section>}
      {page==='sent'&&sent&&<section className="sent-screen"><h1>ส่งดาวแล้ว</h1><p>ขอบคุณที่ฝากกำลังใจให้ใครสักคน</p><div className="sent-field"><SentStar star={sent} paused={modal==='own'} open={()=>setModal('own')}/></div><img className="sent-mascot" src="/assets/mascot-sky.png" alt=""/><button className="secondary" onClick={write}>เขียนดาวอีกดวง</button><button className="link" onClick={()=>go('home')}>กลับหน้าแรก</button></section>}
      {page==='jar'&&<section className="jar-screen"><h1>โถดาวของฉัน</h1><p>เก็บข้อความที่อยากกลับมาอ่านไว้ตรงนี้</p>{api.localJarMode&&<p className="local-note">ดาวอยู่เฉพาะในเบราว์เซอร์นี้ ไม่ซิงก์ข้ามอุปกรณ์ และจะหายเมื่อล้างข้อมูลเว็บไซต์</p>}<div className="jar-scene"><img className="jar-image" src="/assets/jar.png" alt="โถแก้วความทรงจำ"/><div className="jar-stars">{saved.filter(s=>!s.unavailable).slice(0,13).map((s,i)=><motion.button key={s.id} className="jar-star" aria-label={`อ่านดาวที่เก็บ ${i+1}`} style={{left:`${12+(i%3)*27}%`,bottom:`${9+Math.floor(i/3)*17}%`}} initial={s.id===arrival&&!reduced?{y:-320,rotate:-15,opacity:0}:false} animate={{y:0,rotate:0,opacity:1}} transition={{duration:reduced?0:2.05,ease:[.3,.1,.4,1]}} onClick={()=>void openRead(s,'jar')}><img src={starAsset(s.emotion)} alt=""/></motion.button>)}</div><img className="jar-companion" src="/assets/companion.png" alt=""/></div><h2 className="saved-count" aria-live="polite">เก็บไว้แล้ว {saved.length-(arrival?1:0)} ดวง</h2><p>เลือกดาวในโถเพื่ออ่านอีกครั้ง</p><button className="primary" onClick={()=>go('feeling')}>ลองเปิดดาวอีกดวง</button><button className="link" onClick={write}>ฝากดาวให้ใครบางคน →</button><button className="secondary" onClick={()=>setModal('list')}>ดูดาวทั้งหมดในโถ</button>{saved.length===0&&<p>เจอข้อความที่ชอบเมื่อไหร่ เก็บมาไว้ในโถได้เลย</p>}</section>}
      {page==='history'&&<section>{list(history,'history')}<button className="primary" onClick={write}>เขียนดาวอีกดวง</button></section>}
      {page==='admin'&&<section className="admin"><p>อ่านแต่ละข้อความก่อนอนุมัติ เมื่อผ่านแล้ว คนอื่นจึงจะสุ่มเจอได้</p><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{const q=await api.getQueue();setQueue(q.stars);setReports(q.reports);})}>ดูรายการล่าสุด</button><p>{queue.filter(s=>s.status==='pending').length} ข้อความรอตรวจ · {reports.length} รายงาน</p>{queue.length===0&&<p className="empty">ยังไม่มีข้อความเข้ามา</p>}{queue.map(s=><article className="review-card" key={s.id}><span className="badge">{{pending:'รอตรวจ',approved:'อนุมัติแล้ว',rejected:'ไม่อนุมัติ',hidden:'ซ่อนแล้ว'}[s.status]}</span><p className="review-content">{s.content}</p><small>{emotionById(s.emotion).label} · {s.id}</small>{reports.filter(r=>r.message_id===s.id).map((r,i)=><p className="report-flag" key={i}>รายงาน: {r.reason}</p>)}<label>เหตุผลที่เลือกผลนี้<textarea value={reviewReasons[s.id]||''} onChange={e=>setReviewReasons({...reviewReasons,[s.id]:e.target.value})} placeholder="เขียนเหตุผลก่อนอนุมัติ ไม่อนุมัติ หรือซ่อนข้อความ"/></label><div className="review-actions">{(['approved','rejected','hidden'] as const).map(status=><button key={status} className="secondary" disabled={busy||!reviewReasons[s.id]?.trim()} onClick={()=>void run(async()=>{await api.moderate(s.id,status,reviewReasons[s.id]);const q=await api.getQueue();setQueue(q.stars);setReports(q.reports);})}>{{approved:'อนุมัติ',rejected:'ไม่อนุมัติ',hidden:'ซ่อน'}[status]}</button>)}</div></article>)}</section>}
      {page==='privacy'&&<article className="legal"><h1>ความเป็นส่วนตัว</h1><p>ปรับปรุงล่าสุด 8 กันยายน 2026</p><h2>ข้อมูลที่ระบบเก็บ</h2><p>เมื่อคุณส่งดาว ระบบเก็บข้อความ กลุ่มความรู้สึก เวลา และข้อมูลทางเทคนิคที่แปลงเป็นรหัสเพื่อจำกัดการส่งถี่ เราไม่ขอชื่อหรือข้อมูลติดต่อใน Flow นี้ กรุณาอย่าใส่ข้อมูลส่วนตัวลงในข้อความ</p><h2>การใช้และระยะเวลาเก็บข้อมูล</h2><p>ข้อความใหม่จะรอทีมงานตรวจ ก่อนนำไปสุ่มให้ผู้อื่นอ่าน ข้อความที่รอตรวจหรือไม่ผ่านจะลบภายใน 30 วัน รายงานและประวัติการตรวจเก็บไม่เกิน 365 วัน ข้อมูลจำกัดการส่งเก็บไม่เกิน 1 วัน ส่วนข้อความที่อนุมัติจะเก็บจนกว่าจะถูกซ่อนหรือลบ</p><h2>โถดาวในเครื่อง</h2><p>ดาวในโถเก็บอยู่ในเบราว์เซอร์นี้เท่านั้น ไม่ซิงก์ข้ามอุปกรณ์ และจะหายหากล้างข้อมูลเว็บไซต์ ก่อนเปิดดาว ระบบจะตรวจอีกครั้งว่าข้อความยังใช้งานได้</p><h2>แจ้งปัญหา</h2><p>ใช้ปุ่มรายงานใต้ข้อความได้ทันที หรือแจ้งปัญหาผ่าน GitHub โดยไม่ใส่ข้อมูลส่วนตัวหรือข้อความอ่อนไหวในพื้นที่สาธารณะ</p></article>}
      {page==='terms'&&<article className="legal"><h1>ข้อตกลงการใช้งาน</h1><p>Mindfull-OOCA เป็นพื้นที่ทดลองสำหรับแลกเปลี่ยนข้อความให้กำลังใจ ไม่ใช่บริการฉุกเฉิน การวินิจฉัย หรือการรักษาทางการแพทย์</p><h2>ข้อความที่ส่ง</h2><p>ส่งเฉพาะข้อความที่คุณมีสิทธิ์เผยแพร่ ห้ามใส่ข้อมูลส่วนตัว การคุกคาม ความเกลียดชัง โฆษณา หรือเนื้อหาที่อาจทำร้ายผู้อื่น ทีมงานอาจอนุมัติ ซ่อน หรือลบข้อความตามความเหมาะสม</p><h2>ข้อจำกัดของบริการ</h2><p>บริการอยู่ในช่วง Beta ฟีเจอร์อาจเปลี่ยนหรือหยุดชั่วคราว หากคุณหรือคนใกล้ตัวอยู่ในภาวะฉุกเฉิน โปรดติดต่อบริการฉุกเฉินหรือผู้เชี่ยวชาญในพื้นที่ของคุณทันที</p></article>}
    </main>
    {modal==='menu'&&<Modal title="เมนู" close={()=>setModal(null)}><div className="menu-list"><span className="badge">Beta</span><button className="secondary" onClick={()=>void openJar()}>โถดาวของฉัน</button>{(api.authEnabled||api.previewMode)&&<button className="secondary" onClick={()=>void openHistory()}>ดาวที่เคยเขียน</button>}{isMod&&<button className="secondary" onClick={()=>void run(async()=>{const q=await api.getQueue();setQueue(q.stars);setReports(q.reports);go('admin');})}>ตรวจข้อความ</button>}<button className="link" onClick={()=>go('privacy')}>ความเป็นส่วนตัว</button><button className="link" onClick={()=>go('terms')}>ข้อตกลงการใช้งาน</button><a className="link" href={import.meta.env.VITE_FEEDBACK_URL||'https://github.com/'} target="_blank" rel="noreferrer">แจ้งปัญหาผ่าน GitHub</a>{(api.authEnabled||api.previewMode)&&(user?<button className="link" onClick={()=>void run(async()=>{await api.signOut();setUser(null);setSaved([]);setHistory([]);go('home');})}>ออกจากบัญชี{api.previewMode?'ทดลอง':''}</button>:<button className="link" onClick={()=>{setPendingSave(false);setModal('login');}}>ใช้บัญชี{api.previewMode?'ทดลอง':''}</button>)}</div></Modal>}
    {modal==='login'&&<Modal title={api.previewMode?'ลองเก็บดาวไว้ในโถ':'อยากเก็บดาวดวงนี้ไว้ไหม?'} close={()=>{setModal(null);setPendingSave(false);}}><img className="login-mascot" src="/assets/mascot-sky.png" alt=""/><p>{api.previewMode?'ลองเก็บดาวและดูดาวที่เคยเขียนได้ด้วยบัญชีทดลอง ข้อมูลอยู่ในเครื่องนี้ ยังไม่ได้ลงชื่อเข้าใช้ Google':'ตอนนี้ยังลงชื่อเข้าใช้ไม่ได้ แวะมาใหม่ภายหลังได้เลย'}</p>{api.previewMode&&<button className="primary" disabled={busy} onClick={()=>void login()}>ใช้บัญชีทดลองในเครื่อง</button>}</Modal>}
    {modal==='list'&&<Modal title="ดาวที่เก็บไว้" close={()=>setModal(null)}>{list(saved,'jar')}</Modal>}
    {modal==='own'&&sent&&<Modal title="ดาวของคุณ" close={()=>setModal(null)}><Paper star={sent}/></Modal>}
    {modal==='report'&&selected&&<Modal title="รายงานข้อความ" close={()=>setModal(null)}><p>อยากรายงานข้อความนี้เรื่องไหน?</p><fieldset className="report-options"><legend>เหตุผล</legend>{[['hurtful','ข้อความทำร้ายความรู้สึกหรือไม่เหมาะสม'],['personal','มีข้อมูลส่วนตัว'],['spam','โฆษณาหรือสแปม'],['other','เหตุผลอื่น']].map(([value,label])=><label key={value}><input type="radio" name="report" checked={reportReason===value} onChange={()=>setReportReason(value)}/>{label}</label>)}</fieldset>{api.requiresCaptcha&&<Turnstile action="report" resetKey={0} onToken={setReportToken}/>}<button className="primary" disabled={busy||api.requiresCaptcha&&!reportToken} onClick={()=>void run(async()=>{await api.reportStar(selected.id,reportReason,reportToken);setModal(null);setReportToken('');setNotice('ส่งรายงานแล้ว ขอบคุณที่แจ้งให้รู้');})}>ส่งรายงาน</button></Modal>}
  </div>;
}
